### ISSUE TITLE
Зачем нужны CountResult и CountResultEntity?

### ISSUE THREAD

**Issue by tgurskaya96** [Lizka7/Java#3]
https://github.com/Lizka7/Java/blob/22b09cfe661b4b30356c3cf5adcfa3d8cbf28ed3/symbols/src/main/java/com/example/symbols/dto/CountResultEntity.java#L7

**Comment by Lizka7** [comment]
Различие между классами заключается в их целях использования: CountResult для передачи данных, а CountResultEntity для хранения данных в базе данных.
