### ISSUE TITLE
почему кладём 0 в кэш?

### ISSUE THREAD

**Issue by tgurskaya96** [Lizka7/Java#5]
https://github.com/Lizka7/Java/blob/22b09cfe661b4b30356c3cf5adcfa3d8cbf28ed3/symbols/src/main/java/com/example/symbols/controller/CountController.java#L86

**Comment by Lizka7** [comment]
Это делается для того, чтобы обозначить, что результат подсчёта символа для данного cacheKey ещё не был вычислен, и на данный момент значение равно 0. 
Метод calculateCountAsync вызывается асинхронно для вычисления кол-ва символов и сохранения в кэше. Когда результат вычисления становится доступным, он сохраняется в кэше с использованием метода cache.put(cacheKey, count), соответственно значение уже будет обновлено.
