### ISSUE TITLE
Зачем нужен ещё один такой класс?

### ISSUE THREAD

**Issue by tgurskaya96** [Lizka7/Java#6]
https://github.com/Lizka7/Java/blob/22b09cfe661b4b30356c3cf5adcfa3d8cbf28ed3/symbols/src/main/java/com/example/symbols/BulkCountResult.java#L5

**Comment by Lizka7** [comment]
Если Вы говорите о сравнении классов CountResult и BulkCountResult, то между ними есть различия:
CountResult - результат подсчета символа в предоставленной строке, содержит информацию о строке, символе, кол-ве вхождений символа и кол-ве запросов.
BulkCountResult - результат bulk операции, которая включает подсчет символов для списка параметров, содержит список объектов CountResult для каждого параметра, а также дополнительную информацию: кол-во подсчетов, среднее кол-во вхождений символов, максимальное и минимальное кол-во вхождений, а также кол-во запросов.
Таким образом, BulkCountResult включает дополнительную информацию о bulk операции в целом. Чисто теоретически, можно было бы обойтись и без этого класса. Но я увидела выполнение этой лр как-то так.
